---
- hosts: cdt
  remote_user: charles
  vars:
    dest_dir: /home/charles/Project/Blockchain/ansible/nfs
  tasks:

  - name: umount {{dest_dir}}
    shell: umount {{dest_dir}}
    ignore_errors: True
