services:
  peer0.org1.example.com:
    command: peer node start
    container_name: peer0.org1.example.com
    dns: 192.168.3.39
    environment:
    - GODEBUG=netdns=go
    - FABRIC_LOGGING_SPEC=grpc=info:info
    - CORE_CHAINCODE_LOGGING_LEVEL=INFO
    - CORE_CHAINCODE_LOGGING_SHIM=INFO
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer0.org1.example.com
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
    - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ansible_default
    image: hyperledger/fabric-peer:cdt
    ports:
    - 7051:7051
    volumes:
    - /var/run/:/host/var/run/
    - /home/charles/Project/Blockchain/caliper-deploy-tool/benchmarks/config_raft/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  peer0.org2.example.com:
    command: peer node start
    container_name: peer0.org2.example.com
    dns: 192.168.3.39
    environment:
    - GODEBUG=netdns=go
    - FABRIC_LOGGING_SPEC=grpc=info:info
    - CORE_CHAINCODE_LOGGING_LEVEL=INFO
    - CORE_CHAINCODE_LOGGING_SHIM=INFO
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer0.org2.example.com
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
    - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ansible_default
    image: hyperledger/fabric-peer:cdt
    ports:
    - 7078:7051
    volumes:
    - /var/run/:/host/var/run/
    - /home/charles/Project/Blockchain/caliper-deploy-tool/benchmarks/config_raft/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/hyperledger/msp/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  peer1.org1.example.com:
    command: peer node start
    container_name: peer1.org1.example.com
    dns: 192.168.3.39
    environment:
    - GODEBUG=netdns=go
    - FABRIC_LOGGING_SPEC=grpc=info:info
    - CORE_CHAINCODE_LOGGING_LEVEL=INFO
    - CORE_CHAINCODE_LOGGING_SHIM=INFO
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer1.org1.example.com
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
    - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ansible_default
    image: hyperledger/fabric-peer:cdt
    ports:
    - 7061:7051
    volumes:
    - /var/run/:/host/var/run/
    - /home/charles/Project/Blockchain/caliper-deploy-tool/benchmarks/config_raft/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/:/etc/hyperledger/msp/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  peer1.org2.example.com:
    command: peer node start
    container_name: peer1.org2.example.com
    dns: 192.168.3.39
    environment:
    - GODEBUG=netdns=go
    - FABRIC_LOGGING_SPEC=grpc=info:info
    - CORE_CHAINCODE_LOGGING_LEVEL=INFO
    - CORE_CHAINCODE_LOGGING_SHIM=INFO
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer1.org2.example.com
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
    - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=ansible_default
    image: hyperledger/fabric-peer:cdt
    ports:
    - 7081:7051
    volumes:
    - /var/run/:/host/var/run/
    - /home/charles/Project/Blockchain/caliper-deploy-tool/benchmarks/config_raft/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/:/etc/hyperledger/msp/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
version: '3'
