SSH:
  Host: "192.168.3.39"
  Port: 22
  Username: "charles"
  Password: "123456"
Database:
  Mysql:
    Host: "localhost"
    User: "root"
    Password: "123456"
    Port: 3306
    Database: "Auto-Tuning-HLF"
Parameters:
  Orderer:
    - "General_Authentication_TimeWindow"
    - "General_Cluster_SendBufferSize"
    - "General_Keepalive_ServerInterval"
    - "General_Keepalive_ServerMinInterval"
    - "General_Keepalive_ServerTimeout"
    - "Metrics_Statsd_WriteInterval"
  Configtx:
    - "Orderer_BatchTimeout"
    - "Orderer_BatchSize_MaxMessageCount"
    - "Orderer_BatchSize_AbsoluteMaxBytes"
    - "Orderer_BatchSize_PreferredMaxBytes"
  BftConfigtx:
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_RequestBatchMaxCount"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_RequestBatchMaxInterval"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_RequestForwardTimeout"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_RequestComplainTimeout"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_RequestAutoRemoveTimeout"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_ViewChangeResendInterval"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_ViewChangeTimeout"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_LeaderHeartbeatTimeout"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_CollectTimeout"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_IncomingMessageBufferSize"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_RequestPoolSize"
    - "Profiles_ChannelUsingBFT_Orderer_SmartBFT_LeaderHeartbeatCount"
  Peer:
    - "peer_keepalive_minInterval"
    - "peer_keepalive_client_interval"
    - "peer_keepalive_client_timeout"
    - "peer_keepalive_deliveryClient_interval"
    - "peer_keepalive_deliveryClient_timeout"
    - "peer_gossip_membershipTrackerInterval"
    - "peer_gossip_maxBlockCountToStore"
    - "peer_gossip_maxPropagationBurstLatency"
    - "peer_gossip_maxPropagationBurstSize"
    - "peer_gossip_propagateIterations"
    - "peer_gossip_propagatePeerNum"
    - "peer_gossip_pullInterval"
    - "peer_gossip_pullPeerNum"
    - "peer_gossip_requestStateInfoInterval"
    - "peer_gossip_publishStateInfoInterval"
    - "peer_gossip_publishCertPeriod"
    - "peer_gossip_dialTimeout"
    - "peer_gossip_connTimeout"
    - "peer_gossip_recvBuffSize"
    - "peer_gossip_sendBuffSize"
    - "peer_gossip_digestWaitTime"
    - "peer_gossip_requestWaitTime"
    - "peer_gossip_responseWaitTime"
    - "peer_gossip_aliveTimeInterval"
    - "peer_gossip_aliveExpirationTimeout"
    - "peer_gossip_reconnectInterval"
    - "peer_gossip_election_startupGracePeriod"
    - "peer_gossip_election_membershipSampleInterval"
    - "peer_gossip_election_leaderAliveThreshold"
    - "peer_gossip_election_leaderElectionDuration"
    - "peer_gossip_pvtData_pullRetryThreshold"
    - "peer_gossip_pvtData_transientstoreMaxBlockRetention"
    - "peer_gossip_pvtData_pushAckTimeout"
    - "peer_gossip_pvtData_btlPullMargin"
    - "peer_gossip_pvtData_reconcileBatchSize"
    - "peer_gossip_pvtData_reconcileSleepInterval"
    - "peer_gossip_state_checkInterval"
    - "peer_gossip_state_responseTimeout"
    - "peer_gossip_state_batchSize"
    - "peer_gossip_state_blockBufferSize"
    - "peer_gossip_state_maxRetries"
    - "peer_authentication_timewindow"
    - "peer_client_connTimeout"
    - "peer_deliveryclient_reconnectTotalTimeThreshold"
    - "peer_deliveryclient_connTimeout"
    - "peer_deliveryclient_reConnectBackoffThreshold"
    - "peer_discovery_authCacheMaxSize"
    - "peer_discovery_authCachePurgeRetentionRatio"
ConfigPath:
  Orderer: '/home/charles/Project/Blockchain/fabric-samples/config/orderer.yaml'
  Configtx: '/home/charles/Project/Blockchain/fabric-samples/test-network/configtx/configtx.yaml'
  Peer: '/home/charles/Project/Blockchain/fabric-samples/test-network/compose/docker/peercfg/core.yaml'
  BftConfigtx: '/home/charles/Project/Blockchain/fabric-samples/test-network/bft-config/configtx.yaml'
  ConnectionOrg1: "/home/charles/Project/Blockchain/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
